### ISSUE TITLE
404 https://maven.pkg.github.com/djpbarry/

### ISSUE THREAD

**Issue by w34sel** [djpbarry/Giani#5]
404 https://maven.pkg.github.com/djpbarry/

**Comment by w34sel** [comment]
Installed it via ImageJ update Manager:

```
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: imagescience/image/Image
	at net.calm.giani.exec.PipelineBuilder.getDefaultMaximaFinder(PipelineBuilder.java:48)
	at net.calm.giani.ui.GIANIUI.initComponents(GIANIUI.java:102)
	at net.calm.giani.ui.GIANIUI.<init>(GIANIUI.java:67)
	at net.calm.calm.GIANI_.GIANI_$1.run(GIANI_.java:35)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: imagescience.image.Image
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 18 more

```




Afterwards tried to build the jar, but getting this error:
`
404 https://maven.pkg.github.com/djpbarry/`
